import { Activity, Copy, Bookmark, Share, Sparkles } from "lucide-react";
import { Card } from "../components/ui/Card";
import { useState } from "react";
import { motion } from "framer-motion";
import axios from "axios";
import ReactMarkdown from "react-markdown";

export default function AIWorkspace() {
  const [query, setQuery] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [reportText, setReportText] = useState("");

  const handleGenerate = async () => {
    if (!query) return;
    setIsGenerating(true);
    setShowResult(false);
    
    try {
      const API_URL = import.meta.env.VITE_API_URL || "https://obsidian-soc-backend-15k7.onrender.com";
      const response = await axios.post(`${API_URL}/api/v1/ai/generate`, { query });
      setReportText(response.data.report);
      setShowResult(true);
    } catch (error) {
      console.error("Error generating report:", error);
      setReportText("### Error\nFailed to generate report. Please try again.");
      setShowResult(true);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold font-heading">AI Workspace</h1>
          <p className="text-muted mt-1">Generate reports, ask questions, and analyze threats with Gemini.</p>
        </div>
      </div>

      <div className="flex gap-4">
        <input 
          type="text" 
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
          placeholder="E.g. Generate an executive report for a DDoS attack..." 
          className="flex-1 bg-surface border border-border rounded-lg px-4 py-3 focus:outline-none focus:border-primary transition-colors text-sm"
        />
        <button 
          onClick={handleGenerate}
          disabled={isGenerating || !query}
          className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
        >
          {isGenerating ? <div className="w-4 h-4 rounded-full border-2 border-background border-t-transparent animate-spin" /> : <Sparkles className="w-4 h-4" />}
          Generate
        </button>
      </div>

      {/* Document Response */}
      {showResult && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
          <Card className="mt-8 relative group">
            <div className="absolute top-4 right-4 flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <button className="p-1.5 bg-background border border-border rounded text-muted hover:text-text transition-colors"><Copy className="w-4 h-4" /></button>
              <button className="p-1.5 bg-background border border-border rounded text-muted hover:text-text transition-colors"><Bookmark className="w-4 h-4" /></button>
              <button className="p-1.5 bg-background border border-border rounded text-muted hover:text-text transition-colors"><Share className="w-4 h-4" /></button>
            </div>
            
            <div className="flex items-center gap-3 mb-6 pb-4 border-b border-border">
              <div className="p-2 bg-primary/10 rounded">
                <Activity className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h2 className="text-lg font-semibold font-heading">AI Generated Report</h2>
                <div className="text-xs text-muted">Generated by Gemini • Just now based on prompt: "{query}"</div>
              </div>
            </div>

            <div className="prose prose-invert max-w-none text-sm text-muted">
              <ReactMarkdown>{reportText}</ReactMarkdown>
            </div>
          </Card>
        </motion.div>
      )}
    </div>
  );
}
